/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CalculadoraRouteImport } from './routes/calculadora'

const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/calculadora': typeof CalculadoraRoute
}
export interface FileRoutesByTo {
  '/calculadora': typeof CalculadoraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/calculadora': typeof CalculadoraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/calculadora'
  fileRoutesByTo: FileRoutesByTo
  to: '/calculadora'
  id: '__root__' | '/calculadora'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CalculadoraRoute: typeof CalculadoraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CalculadoraRoute: CalculadoraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
